<center><h1 style="color:green">Bag Of Words</center>

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("spam.csv")
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [3]:
df.Category.value_counts()

Category
ham     4825
spam     747
Name: count, dtype: int64

In [4]:
df['spam'] = df['Category'].apply(lambda x: 1 if x =='spam' else 0)

In [5]:
df.shape

(5572, 3)

In [6]:
df.head()

Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

<b>Train test split

In [7]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df.Message, df.spam, test_size=0.2)

In [8]:
len(X_train)

4457

In [9]:
len(X_test)

1115

In [10]:
type(X_train)

pandas.core.series.Series

In [11]:
X_train[:4]

1395                 R we still meeting 4 dinner tonight?
5072                              As in different styles?
3939    WHEN THE FIRST STRIKE IS A RED ONE. THE BIRD +...
2148    Ok. Can be later showing around 8-8:30 if you ...
Name: Message, dtype: object

In [12]:
type(y_train)

pandas.core.series.Series

In [13]:
y_train[:4]

1395    0
5072    0
3939    0
2148    0
Name: spam, dtype: int64

In [25]:
X_train.values

array(['R we still meeting 4 dinner tonight?', 'As in different styles?',
       'WHEN THE FIRST STRIKE IS A RED ONE. THE BIRD + ANTELOPE BEGIN TOPLAY IN THE FIELDOF SELFINDEPENDENCE BELIEVE THIS + THE FLOWER OF CONTENTION WILL GROW.RANDOM!',
       ..., 'Dude got a haircut. Now its breezy up there',
       'See you there!', "Sorry, I'll call later"], dtype=object)

In [14]:
type(X_train.values)

numpy.ndarray

<b>Create bag of words representation using CountVectorizer

In [15]:
from sklearn.feature_extraction.text import CountVectorizer

v = CountVectorizer()

X_train_cv = v.fit_transform(X_train.values)
X_train_cv

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 59230 stored elements and shape (4457, 7709)>

In [22]:
X_train_cv.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [23]:
X_train_cv.toarray()[:2]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [16]:
X_train_cv.toarray()[:2][0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [17]:
X_train_cv.shape

(4457, 7709)

In [29]:
dir(v)

['_CountVectorizer__metadata_request__fit',
 '_CountVectorizer__metadata_request__transform',
 '__annotations__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__sklearn_clone__',
 '__sklearn_tags__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_build_request_for_signature',
 '_char_ngrams',
 '_char_wb_ngrams',
 '_check_feature_names',
 '_check_n_features',
 '_check_stop_words_consistency',
 '_check_vocabulary',
 '_count_vocab',
 '_doc_link_module',
 '_doc_link_template',
 '_doc_link_url_param_generator',
 '_get_default_requests',
 '_get_doc_link',
 '_get_metadata_request',
 '_get_param_names',
 '_get_tags',
 '_limit_features',
 '_more_tags',
 '_parameter_constraints',
 '_r

In [27]:
v.get_feature_names_out().shape

(7709,)

In [26]:
v.get_feature_names_out()

array(['00', '000', '000pes', ..., 'èn', 'ú1', '〨ud'], dtype=object)

In [24]:
v.get_feature_names_out()[1111]

'assume'

In [28]:
v.get_feature_names_out()[1111:1300]

array(['assume', 'assumed', 'asthere', 'asthma', 'astoundingly',
       'astronomer', 'asus', 'asusual', 'at', 'ate', 'athletic', 'athome',
       'atlanta', 'atlast', 'atm', 'attach', 'attached', 'attack',
       'attempt', 'atten', 'attend', 'attended', 'attention', 'attitude',
       'attraction', 'attractive', 'attracts', 'attributed', 'atural',
       'auction', 'audiitions', 'audition', 'audrey', 'audrie', 'august',
       'aunt', 'auntie', 'aunts', 'aunty', 'aust', 'authorise', 'auto',
       'autocorrect', 'av', 'ava', 'availa', 'available', 'avalarr',
       'avatar', 'ave', 'avenge', 'avent', 'avenue', 'avin', 'avo',
       'avoid', 'avoiding', 'avoids', 'await', 'awaiting', 'awake',
       'award', 'awarded', 'away', 'awesome', 'awkward', 'aww', 'awww',
       'ax', 'axis', 'ay', 'ayn', 'b4', 'b4190604', 'b4u', 'b4utele',
       'ba', 'baaaaaaaabe', 'baaaaabe', 'babe', 'babes', 'baby',
       'babygoodbye', 'babyjontet', 'babysit', 'babysitting', 'bac',
       'back', 'backd

In [19]:
v.vocabulary_

{'we': 7383,
 'still': 6455,
 'meeting': 4398,
 'dinner': 2308,
 'tonight': 6944,
 'as': 1087,
 'in': 3631,
 'different': 2291,
 'styles': 6522,
 'when': 7448,
 'the': 6793,
 'first': 2851,
 'strike': 6493,
 'is': 3736,
 'red': 5610,
 'one': 4899,
 'bird': 1364,
 'antelope': 998,
 'begin': 1309,
 'toplay': 6959,
 'fieldof': 2807,
 'selfindependence': 5964,
 'believe': 1316,
 'this': 6833,
 'flower': 2886,
 'of': 4848,
 'contention': 1979,
 'will': 7485,
 'grow': 3237,
 'random': 5530,
 'ok': 4875,
 'can': 1632,
 'be': 1277,
 'later': 4012,
 'showing': 6096,
 'around': 1075,
 '30': 430,
 'if': 3587,
 'you': 7673,
 'want': 7347,
 'cld': 1828,
 'have': 3339,
 'drink': 2424,
 'before': 1305,
 'wld': 7532,
 'prefer': 5336,
 'not': 4788,
 'to': 6908,
 'spend': 6345,
 'money': 4533,
 'on': 4893,
 'nosh': 4786,
 'don': 2380,
 'mind': 4452,
 'doing': 2372,
 'that': 6790,
 'nxt': 4824,
 'wk': 7524,
 'right': 5748,
 'second': 5935,
 'gotta': 3194,
 'hit': 3427,
 'people': 5106,
 'up': 7152,
 'hou

In [30]:
X_train_np = X_train_cv.toarray()

In [31]:
X_train_np[0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [43]:
v.get_feature_names_out()[2308]

'dinner'

In [44]:
np.where(X_train_np[0]!=0)

(array([2308, 4398, 6455, 6944, 7383], dtype=int64),)

In [45]:
X_train[:4]

1395                 R we still meeting 4 dinner tonight?
5072                              As in different styles?
3939    WHEN THE FIRST STRIKE IS A RED ONE. THE BIRD +...
2148    Ok. Can be later showing around 8-8:30 if you ...
Name: Message, dtype: object

In [46]:
X_train[:4][1395]

'R we still meeting 4 dinner tonight?'

In [47]:
X_train_np[:4] 

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [48]:
X_train_np[0][2308]

1

<b>Train the naive bayes model

In [49]:
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()
model.fit(X_train_cv, y_train)

MultinomialNB()

In [50]:
X_test_cv = v.transform(X_test)

<b>Evaluate Performance

In [51]:
from sklearn.metrics import classification_report

y_pred = model.predict(X_test_cv)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.98      0.99      0.99       961
           1       0.96      0.88      0.92       154

    accuracy                           0.98      1115
   macro avg       0.97      0.94      0.96      1115
weighted avg       0.98      0.98      0.98      1115



In [52]:
emails = [
    'Hey mohan, can we get together to watch footbal game tomorrow?',
    'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!'
]

emails_count = v.transform(emails)
model.predict(emails_count)

array([0, 1], dtype=int64)

0 means ham and 1 means spam

<b>Train the model using sklearn pipeline and reduce number of lines of code

In [53]:
from sklearn.pipeline import Pipeline

clf = Pipeline([
    ('vectorizer', CountVectorizer()),
    ('nb', MultinomialNB())
])

In [54]:
clf.fit(X_train, y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [55]:
y_pred = clf.predict(X_test)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.98      0.99      0.99       961
           1       0.96      0.88      0.92       154

    accuracy                           0.98      1115
   macro avg       0.97      0.94      0.96      1115
weighted avg       0.98      0.98      0.98      1115



In [57]:
emails = [
    'Hey mohan, can we get together to watch footbal game tomorrow?',
    'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!'
]

clf.predict(emails)

array([0, 1], dtype=int64)

0 means ham and 1 means spam