<center><h1>Bag of Words</center>

- In this Exercise, we are going to classify whether a given movie review is positive or negative.
- we are going to use Bag of words for pre-processing the text and apply different classification algorithms.
- Sklearn CountVectorizer has the inbuilt implementations for Bag of Words.

<b>Load Dataset

In [2]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.ensemble import RandomForestClassifier
from  sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.pipeline import Pipeline
from sklearn.metrics import classification_report

In [3]:
df = pd.read_csv("movies_sentiment_data.csv")

#2. print the shape of the data
print(df.shape)

#3. print top 5 datapoints
df.head()

(19000, 2)


review sentiment
0  I first saw Jake Gyllenhaal in Jarhead (2005) ...  positive
1  I enjoyed the movie and the story immensely! I...  positive
2  I had a hard time sitting through this. Every ...  negative
3  It's hard to imagine that anyone could find th...  negative
4  This is one military drama I like a lot! Tom B...  positive

In [5]:
df['sentiment'].value_counts()

sentiment
positive    9500
negative    9500
Name: count, dtype: int64

In [6]:
df['Category'] = df['sentiment'].apply(lambda x: 1 if x =='positive' else 0)

In [7]:
df.head()

review sentiment  Category
0  I first saw Jake Gyllenhaal in Jarhead (2005) ...  positive         1
1  I enjoyed the movie and the story immensely! I...  positive         1
2  I had a hard time sitting through this. Every ...  negative         0
3  It's hard to imagine that anyone could find th...  negative         0
4  This is one military drama I like a lot! Tom B...  positive         1

In [8]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df.review, df.Category, test_size=0.2)

In [9]:
len(X_train)

15200

In [10]:
len(X_test)

3800

<b>Exercise-1</b>

- using sklearn pipeline module create a classification pipeline to classify the movie review's positive or negative.
Note:

- use CountVectorizer for pre-processing the text.

- use Random Forest as the classifier with estimators as 50 and criterion as entropy.

- print the classification report.

In [11]:
clf = Pipeline([
    ('vectorizer', CountVectorizer()),                                                    #initializing the vectorizer
    ('random_forest', (RandomForestClassifier(n_estimators=50, criterion='entropy')))      #using the RandomForest classifier
])



#2. fit with X_train and y_train
clf.fit(X_train, y_train)


#3. get the predictions for X_test and store it in y_pred
y_pred = clf.predict(X_test)


#4. print the classfication report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.81      0.84      0.82      1899
           1       0.83      0.81      0.82      1901

    accuracy                           0.82      3800
   macro avg       0.82      0.82      0.82      3800
weighted avg       0.82      0.82      0.82      3800



As we can see above, for both the classes (positive and negative sentiment) we got more than 80% precision, recall and f1- score. This seems to be an acceptable performance.

In [63]:
sentiments = [
    'It was a good movie and we love this',
    'Movie was boring and it waste our time'
]

In [16]:
clf.predict(sentiments)

array([1, 0], dtype=int64)

In [62]:
a = 'It was a good movie and we love this'
b = 'Movie was boring and it waste our time'

In [34]:
res = clf.predict([a])
if res == 1:
    print("Positive")
else:
    print("Negative")

Positive


In [35]:
res = clf.predict([b])
if res == 1:
    print("Positive")
else:
    print("Negative")

Negative


<b>Exercise-2</b>

- using sklearn pipeline module create a classification pipeline to classify the movie review's positive or negative..
Note:

- use CountVectorizer for pre-processing the text.
- use KNN as the classifier with n_neighbors of 10 and metric as 'euclidean'.
- print the classification report.

In [54]:
clf = Pipeline([
                
     ('vectorizer', CountVectorizer()),   
      ('KNN', (KNeighborsClassifier(n_neighbors=10, metric = 'euclidean')))   #using the KNN classifier with 10 neighbors 
])


#2. fit with X_train and y_train
clf.fit(X_train, y_train)


#3. get the predictions for X_test and store it in y_pred
y_pred = clf.predict(X_test)


#4. print the classfication report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.63      0.64      0.64      1899
           1       0.64      0.63      0.63      1901

    accuracy                           0.64      3800
   macro avg       0.64      0.64      0.64      3800
weighted avg       0.64      0.64      0.64      3800



here the performance of various metrics (precision, recall etc.) seem to be lower (~60 %).So it's not a good choice

In [57]:
sentiments = [
    'It was a good movie and we love this',
    'Movie was boring and it waste our time'
]

In [58]:
clf.predict(sentiments)

array([0, 0], dtype=int64)

In [59]:
a = 'It was a good movie and we love this'
b = 'Movie was boring and it waste our time'

In [60]:
res = clf.predict([a])
if res == 1:
    print("Positive")
else:
    print("Negative")

Negative


In [61]:
res = clf.predict([b])
if res == 1:
    print("Positive")
else:
    print("Negative")

Negative


It's make a wrong prediction

<b>Exercise-3</b>

- using sklearn pipeline module create a classification pipeline to classify the movie review's positive or negative..
Note:

- use CountVectorizer for pre-processing the text.
- use Multinomial Naive Bayes as the classifier.
- print the classification report.

In [64]:
clf = Pipeline([
                
     ('vectorizer', CountVectorizer()),   
      ('Multi NB', MultinomialNB())   #using the Multinomial Naive Bayes classifier 
])


#2. fit with X_train and y_train
clf.fit(X_train, y_train)


#3. get the predictions for X_test and store it in y_pred
y_pred = clf.predict(X_test)


#4. print the classfication report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.82      0.89      0.85      1899
           1       0.88      0.81      0.84      1901

    accuracy                           0.85      3800
   macro avg       0.85      0.85      0.85      3800
weighted avg       0.85      0.85      0.85      3800



MultinomialNB model for both the classes (positive and negative sentiment) we got more than 80% precision, recall and f1- score and performed equally good with Random Forest. This seems to be an acceptable performance.

In [65]:
sentiments = [
    'It was a good movie and we love this',
    'Movie was boring and it waste our time'
]

In [67]:
clf.predict(sentiments)

array([1, 0], dtype=int64)

In [68]:
a = 'It was a good movie and we love this'
b = 'Movie was boring and it waste our time' 

In [69]:
res = clf.predict([a])
if res == 1:
    print("Positive")
else:
    print("Negative")

Positive


In [70]:
res = clf.predict([b])
if res == 1:
    print("Positive")
else:
    print("Negative")

Negative


<b>Why model like KNN fails to produce good results unlike RandomForest and MultinomialNB?</b>
- As Machine learning algorithms does not work on Text data directly, we need to convert them into numeric vector and feed that into models while training.
- In this process, we convert text into a very high dimensional numeric vector using the technique of Bag of words.
- Model like K-Nearest Neighbours(KNN) doesn't work well with high dimensional data because with large number of dimensions, it becomes difficult for the algorithm to calculate distance in each dimension. In higher dimensional space, the cost to calculate distance becomes expensive and hence impacts the performance of model.
- The easy calculation of probabilities for the words in corpus(Bag of words) and storing them in contigency table is the major reason for the Multinomial NaiveBayes to be a text classification friendly algorithm.
- As Random Forest uses Bootstrapping(Row and column Sampling) with many decision tree and overcomes the high variance and overfitting of high dimensional data and also uses feature importance of words for better classifing the categories.
- Machine Learning is like trial and error scientific method, where we keep trying all the possible algorithms we have and select the one which give good results and satisfy the requirements like latency, interpretability etc.